import { getMockAIMarketSummary } from '@/lib/market-data/mock-data'
import { Sparkles, CheckCircle } from 'lucide-react'

export async function AIMarketSummarySection() {
  const summary = getMockAIMarketSummary()

  return (
    <section>
      <h2 className="text-2xl font-bold text-text-primary mb-6 flex items-center gap-2">
        <Sparkles className="w-5 h-5 text-brand-400" />
        AI Daily Market Summary
      </h2>

      <div className="glass-card p-6 border-brand-500/20">
        {/* Header */}
        <div className="flex items-start justify-between gap-4 mb-5">
          <div>
            <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-brand-500/10 border border-brand-500/30 text-brand-400 text-xs font-semibold mb-3">
              <Sparkles className="w-3 h-3" />
              Generated by StockLens AI
              <span className="text-brand-400/60">· {new Date(summary.generatedAt).toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' })}</span>
            </div>
            <p className="text-text-secondary leading-relaxed">{summary.summary}</p>
          </div>
        </div>

        {/* Bullet Points */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-3 mb-5">
          {summary.bullets.map((bullet, i) => (
            <div key={i} className="flex items-start gap-3 p-3 rounded-xl bg-white/[0.03] border border-white/[0.04]">
              <CheckCircle className="w-4 h-4 text-brand-400 shrink-0 mt-0.5" />
              <span className="text-sm text-text-secondary">{bullet}</span>
            </div>
          ))}
        </div>

        {/* Sectors */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div>
            <div className="text-xs font-semibold text-bull uppercase tracking-wider mb-2">Strong Sectors</div>
            <div className="flex flex-wrap gap-2">
              {summary.strongSectors.map(s => (
                <span key={s} className="px-2.5 py-1 rounded-lg bg-bull/10 text-bull text-xs font-medium border border-bull/20">{s}</span>
              ))}
            </div>
          </div>
          <div>
            <div className="text-xs font-semibold text-bear uppercase tracking-wider mb-2">Weak Sectors</div>
            <div className="flex flex-wrap gap-2">
              {summary.weakSectors.map(s => (
                <span key={s} className="px-2.5 py-1 rounded-lg bg-bear/10 text-bear text-xs font-medium border border-bear/20">{s}</span>
              ))}
            </div>
          </div>
        </div>

        <div className="divider" />
        <p className="text-xs text-text-muted">
          <strong className="text-warn">Market Mood:</strong> {summary.marketMood}
        </p>
      </div>
    </section>
  )
}
